<?php

namespace App\Modules\User\Providers;

use App\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}

